# -*- coding: utf-8 -*-
"""Prodigy_ML_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlroOyNk4gH3hMA8eOfKfVW_cirDDLzh
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

data = pd.read_csv("/content/Mall_Customers.csv")

data.head()

data.info()

data.isna().sum()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["Genre"] = le.fit_transform(data["Genre"])

data.head()

import seaborn as sns

sns.heatmap(data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

data_copy=data.copy()
customer=data_copy.pop('CustomerID')
data_copy

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data_copy)
data_scaled

data_2 = pd.DataFrame(data_scaled, columns=data_copy.columns)
data_2

from sklearn.cluster import KMeans
cluster =list(range(1,11))
ssd=[]
for i in cluster:
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(data_2)
  ssd.append(kmeans.inertia_)

plt.plot(cluster,ssd,'bx-')
plt.xlabel('Clusters')
plt.ylabel('SSD')
plt.title('Elbow Method')

model=KMeans(n_clusters=5,init='k-means++',random_state=42)
model.fit(data_2)

model.labels_

data['Labels']= model.labels_

data.head()

data['Labels'].value_counts(ascending= True)